spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtsecurity
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      format_sql: true
    database: postgresql
